name: Update wiki

on: 
  push:
    branches:
      - main

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 3.1
        
      - name: Setup plantuml
        run: |
          wget https://github.com/plantuml/plantuml/releases/download/v1.2023.6/plantuml-1.2023.6.jar -O /tmp/plantuml.jar
          
          echo -e "#"'!'"/bin/bash\njava -Djava.awt.headless=true -jar /tmp/plantuml.jar \${@}\nexit \$?" > /tmp/plantuml
          chmod +x /tmp/plantuml
          export PATH="$PATH:/tmp"
          
          pip install pandoc-plantuml-filter
          sudo apt install -y graphviz

          cd docs
          for file in *.md; do
            echo "Converting $file.."
            pandoc \
              -f markdown \
              -t gfm \
              -o $file \
              --citeproc --bibliography=bibliography.bib --csl=apa.csl \
              --filter pandoc-plantuml \
              $file
          done

      - name: github-docs-to-wiki
        uses: StephanStanisic/github-docs-to-wiki@master
        with:
          githubToken: ${{ secrets.PAT_TOKEN }}
          defaultBranch: 'main'
          customCommitMessageFormat: 'Update wiki to {shaShort}'
          rootDocsFolder: 'docs'

            
